// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmk1Ih9XFoqzi-mkH-KcS9IcucXeJDID0',
    appId: '1:452700561364:web:6555cc2c84ff5d60dac041',
    messagingSenderId: '452700561364',
    projectId: 'balanced-5dd69',
    authDomain: 'balanced-5dd69.firebaseapp.com',
    storageBucket: 'balanced-5dd69.firebasestorage.app',
    measurementId: 'G-2KEZQLD0PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzGfLGcrKGy5bFyVxhwd_48DK4emW81oo',
    appId: '1:452700561364:android:5d196577bb5d0db2dac041',
    messagingSenderId: '452700561364',
    projectId: 'balanced-5dd69',
    storageBucket: 'balanced-5dd69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCImriHkXzLfDamwXcJ2kVJY_w_zYglVQY',
    appId: '1:452700561364:ios:a373980fdd801c13dac041',
    messagingSenderId: '452700561364',
    projectId: 'balanced-5dd69',
    storageBucket: 'balanced-5dd69.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCImriHkXzLfDamwXcJ2kVJY_w_zYglVQY',
    appId: '1:452700561364:ios:a373980fdd801c13dac041',
    messagingSenderId: '452700561364',
    projectId: 'balanced-5dd69',
    storageBucket: 'balanced-5dd69.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmk1Ih9XFoqzi-mkH-KcS9IcucXeJDID0',
    appId: '1:452700561364:web:d1f0d550fbab509cdac041',
    messagingSenderId: '452700561364',
    projectId: 'balanced-5dd69',
    authDomain: 'balanced-5dd69.firebaseapp.com',
    storageBucket: 'balanced-5dd69.firebasestorage.app',
    measurementId: 'G-4VQD64SS41',
  );
}
