name: balanced_meal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  google_sign_in: ^6.1.5
  provider: ^6.1.5
  flutter_riverpod: ^2.4.9
  cached_network_image: ^3.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.1
  uuid: ^4.5.1
  table_calendar: ^3.0.9
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  google_maps_flutter: ^2.12.2
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#FFA000"  
  image: assets/images/balanced_meal.png
  android: true
  ios: true
  web: true 
  android_gravity: center
  ios_content_mode: center
  android_12: 
    image: assets/images/balanced_meal.png
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/balanced_meal.png
